intel/iot-rest-api-server

- package.json
Signed-off-by: Zhiqiang Zhang <zhiqiang.zhang@intel.com>
> package.json: Update license per LICENSE file

- README.md
- package.json
Signed-off-by: Zhiqiang Zhang <zhiqiang.zhang@intel.com>
> Update using 01org

- index.js
- package.json
- test/oic-api-tester.js
Signed-off-by: sakari.poussa@intel.com
> Use mimimist for command line args to save 11M disk space

- routes/oicRoutes.js
device.client doesn't exist anymore, so use device for the discovery.
> Fix device discovery

- package.json
Signed-off-by: Sakari Poussa <sakari.poussa@intel.com>
> package.json: update iotivity-node dependency to latest

- index.js
- package.json
Add socket activation support directly and remove the module dependency.
> Remove systemd module dependency

- handlers/ocfHandler.js
- package.json
This updates the ocfHandler implementation to latest OIC JS spec and also iotivity-node dependency to v1.1.0-1.
> Update the implementation to latest OIC JS spec.

- test/oic-api-tester.js
Parse the command line args directly without using mimimist module.
> Drop mimimist module dependency from oic-api-tester.js

- handlers/ocfHandler.js
> Set Content-Type to application/json in observe request

- package.json
> package.json: Update iotivity-node dependency to v1.1.0-4

- handlers/ocfHandler.js
- oic/oic.js
Add platform discovery API /oic/p support to retrieve the
information about the OIC platform.
> Add support for /oic/p

- README.md
> README.md: Fix doc and test folders links

- package.json
> package.json: Update iotivity-node dependency to v1.1.1-3

- README.md
- handlers/ocfHandler.js
- oic/oic.js
- package.json
- test/README.md
- test/oic-api-tester.js
- test/oic-post
- test/post-light-values.json
- test/put-light-values.json
Update REST API server implementation to the latest OCF JS spec and IoTivity 1.2.0-1.
This branch also includes a change that replaces PUT with POST for resource update as defined in the OCF specification.
> Update implementation to the latest OCF JS spec and IoTivity 1.2.0-1

- snapcraft.yaml
Signed-off-by: Sakari Poussa <sakari.poussa@intel.com>
> Add BLE to snap

- snapcraft.yaml
Add another BLE tool to the snap.
> snap: add hcitool

- package.json
> package.json: Update iotivity-node dependency to v1.2.0-2

- package.json
Signed-off-by: Sakari Poussa <sakari.poussa@intel.com>
> package.json: publish new version

- package.json
> package.json: Update iotivity-node dependency to v1.2.0-5

- package.json
Prepare to publish new version.
> package.json: version 0.4.0

- package.json
> package.json: Update iotivity-node dependency to v1.2.1-1

- handlers/ocfHandler.js
Fixes https://github.com/01org/iot-rest-api-server/issues/59
> Fix typo in log message

- .dockerignore
- Dockerfile
- package.json
Build:
docker build --build-arg http_proxy=$http_proxy --build-arg https_proxy=$https_proxy -t <userid>/<image-name> .
Run:
docker run -d -p 8000:8000 <userid>/<image-name>
> Add support for building docker image

- package.json
- iotivity-node:  1.2.1-1 to 1.3.0-0
- Package version: 0.5.0 to to 0.6.0
> package.json: Update iotivity-node dependency and package version

- handlers/ocfHandler.js
This adds support for query-oriented resource discovery.
e.g: /oic/res?rt=core.light
> ocfHandler: Add support for query-oriented resource discovery

- .gitignore
Signed-off-by: John Andersen <john.s.andersen@intel.com>
> .gitignore: Ignore vim .swp files

- README.md
- server.js
> server: change configuration to listen on localhost interface only

- README.md
- handlers/ocfHandler.js
- oic/oic.js
- package.json
- test/README.md
- test/oic-api-tester.js
* Fix the /oic/res response to align with the spec
* Expose endpoints information
> Fix the /oic/res response to align with the spec
